# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes
 
handlers:
- url: /
  static_files: dist/tesisproj/index.html
  upload: dist/tesisproj/index.html
 
- url: /
  static_dir: dist/tesisproj
 
# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json
- ^(.*/)?.patch$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# [END runtime]